name: CI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['*']

jobs:

    tests:
        name: Tests - PHP ${{ matrix.php }} ${{ matrix.dependency-version }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            matrix:
                php: [ '8.0', '8.1', '8.2', '8.3' ]
                dependency-version: [ '' ]
                include:
                    -   php: '8.0'
                        dependency-version: '--prefer-lowest'
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    tools: composer:v2
                    coverage: none
                    # Enable apcu
                    extensions: apcu
                    ini-values: apc.enable_cli=1
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: php-${{ matrix.php }}-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-${{ matrix.php }}-composer-locked-
            -   name: Install PHP dependencies
                if: matrix.php != '8.1'
                run: composer update ${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --no-suggest
            -   name: 'Install PHP dependencies on PHP 8.1 (TODO: remove that)'
                if: matrix.php == '8.1'
                run: composer update --ignore-platform-reqs ${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-progress --no-suggest
            -   name: PHPUnit
                run: vendor/bin/phpunit

    cs:
        name: Coding standards
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    tools: composer:v2, cs2pr
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: php-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-composer-locked-
            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-progress --no-suggest
            -   name: PHP CS Fixer
                run: vendor/bin/php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

    psalm:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    tools: composer:v2, cs2pr
                    coverage: none
            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ~/.composer/cache
                    key: php-composer-locked-${{ hashFiles('composer.lock') }}
                    restore-keys: php-composer-locked-
            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-progress --no-suggest
            -   name: Psalm
                run: vendor/bin/psalm --output-format=checkstyle | cs2pr
